const bcrypt = require("bcryptjs");

const data = {
  users: [
    {
      name: "Hatim",
      email: "admin@hatim.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: true,
    },
    {
      name: "Bayan",
      email: "user@bayan.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Slim Shirt",
      category: "Clothes",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Clothes",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 13,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Clothes",
      price: 110,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pants",
      category: "Clothes",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Puma Slim Pants",
      category: "Clothes",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.3,
      numReviews: 12,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pants",
      category: "Clothes",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      countInStock: 20,
      rating: 4.5,
      numReviews: 28,
      name: "ASUS L203MA Laptop",
      brand: "ASUS",
      category: "Electronics",
      description:
        "ASUS L203MA-DS04 VivoBook L203MA Laptop, 11.6” HD Display, Intel Celeron Dual Core CPU, 4GB RAM, 64GB Storage, USB-C, Windows 10 Home In S Mode, Up To 10 Hours Battery Life, One Year Of Microsoft 365",
      price: 295,
    },
    {
      countInStock: 10,
      rating: 5,
      numReviews: 0,
      name: "ASUS F512JA-AS34 Laptop",
      brand: "ASUS",
      category: "Electronics",
      description:
        "ASUS F512JA-AS34 VivoBook 15 Thin and Light Laptop, 15.6” FHD Display, Intel i3-1005G1 CPU, 8GB RAM, 128GB SSD, Backlit Keyboard, Fingerprint, Windows 10 Home in S Mode, Slate Gray",
      price: 485,
    },
    {
      countInStock: 15,
      rating: 4.5,
      numReviews: 10,
      name: "Acer A115-31-C2Y3 Laptop",
      brand: "Acer",
      category: "Electronics",
      description:
        'Acer Aspire 1 A115-31-C2Y3, 15.6" Full HD Display, Intel Celeron N4020, 4GB DDR4, 64GB eMMC, 802.11ac Wi-Fi 5, Up to 10-Hours of Battery Life, Microsoft 365 Personal, Windows 10 in S mode',
      price: 329,
    },
    {
      countInStock: 15,
      rating: 4,
      numReviews: 8,
      name: "Lenovo 2020 IdeaPad Laptop",
      brand: "Lenovo",
      category: "Electronics",
      description:
        '2020 Lenovo IdeaPad Laptop ComputerAMD A6-9220e 1.6GHz 4GB Memory 64GB eMMC Flash Memory 14" AMD Radeon R4 AC WiFi Microsoft Office 365 Platinum Gray Windows 10 Home',
      price: 259,
    },
    {
      countInStock: 12,
      rating: 4.5,
      numReviews: 23,
      name: "ASUS TUF Gaming Laptop",
      brand: "ASUS",
      category: "Electronics",
      description:
        "ASUS TUF Gaming Laptop, 15.6” 144Hz Full HD IPS-Type Display, Intel Core i7-9750H Processor, GeForce GTX 1650, 8GB DDR4, 512GB PCIe SSD, Gigabit Wi-Fi 5, Windows 10 Home, FX505GT-AB73",
      price: 839,
    },
    {
      countInStock: 30,
      rating: 3.5,
      numReviews: 10,
      name: "JavaScript and JQuery",
      brand: "Jon Duckett",
      category: "Books",
      description:
        "JavaScript and JQuery: Interactive Front-End Web Development 1st Edition This full-color book will show you how to make your websites more interactive and your interfaces more interesting and intuitive.",
      price: 20,
    },
    {
      countInStock: 15,
      rating: 4,
      numReviews: 13,
      name: "Introduction to Algorithms",
      brand: "Thomas H. Cormen",
      category: "Books",
      description: "Introduction to Algorithms, 3rd Edition (The MIT Press)",
      price: 60,
    },
    {
      countInStock: 15,
      rating: 4.5,
      numReviews: 18,
      name: "Node.js Design Patterns",
      brand: "Mario Casciaro",
      category: "Books",
      description:
        "Node.js Design Patterns: Design and implement production-grade Node.js applications using proven patterns and techniques, 3rd Edition",
      price: 49,
    },
  ],
};

module.exports = data;
